# L3 제어 검증 결과 — 2026-09-14

모든 수치는 실제 실행 결과다. 재현 명령과 출력 파일을 각 절에 적어 두었다.

요약 네 줄:

1. `heading_rate_dps` 는 psi wrap 버그였다. 물리 문제가 아니다.
2. 협조선회 요레이트 식 `g·tanφ/V` 는 **선회율(ψ̇)** 이지 **body 요레이트(r)** 가 아니다. 뱅크 60도에서 이론값의 2.5배를 지령했다.
3. 45~60도 러더 포화는 **기체 한계가 아니다.** 지령식만 고치면 포화가 97% → 3% 로 사라진다.
4. **9G 는 이 플랜트에서 도달 불가능하다** — 제어기 문제가 아니라 15000ft/400KCAS 에서 기체가 낼 수 있는 최대 Nz 가 6.7G 다. 그리고 지금까지 쓰던 G 계산식이 최대 1.8G 과대평가하고 있었다.

---

## [1] `heading_rate_dps` 검증

```
python scripts/verify_heading_rate.py      ->  results/heading_rate_verification.csv
```

### 결론: psi wrap 버그. 계산식은 `run_indi_step_sweep_coordinated.py` 한 곳에만 있었다

문제의 코드(수정 전):

```python
psi0 = p["attitude/psi-rad"]                                   # 트림 직후
...
heading_rate = (np.rad2deg(p["attitude/psi-rad"]) - np.rad2deg(psi0)) / t_total
```

JSBSim `attitude/psi-rad` 은 **[0, 2π) 로 감긴다**. 그리고 `set_ic(psi_deg=0)` 후 트림하면
`psi0 = 6.283185307179586 rad = 정확히 360.0deg` 다(직접 확인). 선회를 시작하면 psi 는
0 쪽에서 증가하므로 차분이 항상 **−360deg** 를 덤으로 달고 나온다.

| 지표 | 단위 | 부호 규약 |
|---|---|---|
| `heading_rate_dps` (수정 후) | deg/s | `np.unwrap` 후 (ψ_end − ψ_0)/T. **전 구간 평균**이라 롤인 과도구간이 섞여 정상상태보다 낮게 나온다 |
| `heading_rate_naive_dps` | deg/s | 기존 식 그대로 보존 — 과거 결과와 대조용 |
| `psidot_ss_dps` | deg/s | JSBSim `velocities/psidot-rad_sec` 의 마지막 25% 평균. **독립 측정치** |

세 방법 실측 대조 (10000ft / 350KCAS, k_scale=1.0, filt 25Hz):

| 뱅크 | naive(기존) | unwrap | psidot 실측 | naive − unwrap |
|---:|---:|---:|---:|---:|
| 0° | −45.000 | 0.000 | 0.000 | −45.000 |
| 15° | −44.301 | 0.699 | 0.737 | −45.000 |
| 30° | −43.597 | 1.403 | 1.407 | −45.000 |
| 45° | −42.713 | 2.287 | 2.331 | −45.000 |
| 60° | −41.275 | 3.725 | 4.042 | −45.000 |

차이가 **모든 행에서 정확히 −45.000 dps = −360deg / 8s** 다. 오프셋 하나로 전부 설명된다.

수정 후 선회율은 뱅크에 따라 단조 증가하고(0 → 3.73), 독립 측정치 `psidot` 와 일치한다.
뱅크 0에서 0.000 이다. 물리적으로 맞다.

### 협조선회 요레이트 `r_sp` 검증 — 여기가 진짜 문제였다

코드가 넣는 값:

```python
omega_sp[2] = G_FT_S2 * np.tan(phi) / max(v_fps, 1.0)      # = g·tanφ/V
```

`g·tanφ/V` 는 **수평 협조선회의 선회율 ψ̇** 이다. 그런데 `omega_sp[2]` 는 INDI 가 받는
**body 요레이트 r** 이다. 둘은 다르다. 협조선회 기구학은

```
ψ̇ = g·tanφ / V
r  = ψ̇ · cosθ · cosφ        ( = g·sinφ·cosθ / V )
q  = ψ̇ · cosθ · sinφ
```

즉 올바른 값은 `g·sinφ·cosθ/V` 이고, 현행 식은 **1/cosφ 배만큼 크다**. 실측:

| 뱅크 | `r_sp` 지령 | `r` 이론 (ψ̇·cosθ·cosφ) | `r` 실제 | 지령/이론 | 러더 포화 | β 정상상태 |
|---:|---:|---:|---:|---:|---:|---:|
| 15° | 0.726 | 0.712 | 0.713 | **1.02** | 0.9% | 0.10° |
| 30° | 1.561 | 1.217 | 1.218 | **1.28** | 78.1% | 0.57° |
| 45° | 2.703 | 1.639 | 1.640 | **1.65** | 94.9% | 1.11° |
| 60° | 4.750 | 1.972 | 1.964 | **2.41** | 96.8% | 1.50° |

(단위 deg/s. 10000ft/350KCAS, k_scale=1.0, filt 25Hz, 정상상태 = 마지막 2초 평균)

**실제 r 은 이론값과 0.2% 안에서 일치한다.** 기체는 지극히 정상적인 선회를 하고 있다.
어긋난 건 지령뿐이다. INDI 는 물리적으로 도달 불가능한 r 을 쫓느라 러더를 스톱까지
적분해 밀어붙인다(INDI 는 `u = u_filt_prev + du` 형태의 순수 적분기라, 아무리 작아도
지속되는 오차가 있으면 명령이 스톱까지 램프한다).

포화율이 뱅크에 따라 급증하는 지점(15°→30°: 0.9% → 78%)이 지령/이론 비가 1.02 → 1.28
로 벌어지는 지점과 정확히 일치한다.

### 수정 내용

`run_indi_step_sweep_coordinated.py`:

* heading_rate 를 `np.unwrap` 기반으로 교체, `heading_rate_naive_dps` / `psidot_ss_dps` 컬럼 추가
* `--yaw-ff {tan,sin}` 추가 — 기본값은 **재현성을 위해 `tan`(원본 그대로)** 으로 뒀다. 바꾸려면 명시적으로 `--yaw-ff sin`
* `--alt-ft` / `--kcas` 추가

---

## [2] 안정 / 열화 / 불안정 3구간 판정 기준

```
python scripts/classify_stability_bands.py
   ->  results/stability_boundary_summary_classified.csv
```

구현은 `scripts/sweep_diagnostics.py` 의 `classify_band()` (근거는 그 파일 주석에 길게 적어 뒀다).

### 왜 새 기준이 필요한가

기존 `oscillating` 플래그는 **마지막 3초만** 본다. 정상상태 리밋사이클 검출기다. 과도응답에서
크게 튀었다가 결국 가라앉는 케이스를 전부 놓친다. 지적하신 `G5_k1.6_f50` 이 정확히 그 경우다:
`oscillating=0` 인데 overshoot 2.906G, settle 5.81s, rms_q 1.722dps.

### 기준

**정규화 기준값 = 같은 `filt_hz` 의 최저 이득(`k_scale`=1.0) 행.**

`overshoot_g` 의 절대값은 filt_hz 만으로도 기준선이 28% 움직인다(k=1.0 에서 f10=0.1175,
f50=0.1499). 절대 임계를 쓰면 그 차이가 판정에 섞인다. 필터를 고정하고 이득만 올린
**배수 ρ** 를 쓰면 필터 효과가 소거되고 "이득을 올려서 나빠진 양"만 남는다.

| 구간 | 조건 |
|---|---|
| **불안정** | `oscillating=1` 또는 `g_exceeded=1` |
| **열화** | 위가 아니면서 `max(ρ_overshoot, ρ_settle, ρ_rms) > 1.5` |
| **안정** | 나머지 |

### 임계 1.5 의 근거

`oscillating=0` 인 23개 조합의 ρ_overshoot 분포:

```
1.00 1.00 1.00 1.00 1.00 1.02 1.02 1.03 1.03 1.04 1.05 1.05 1.07
1.09 1.09 1.13 1.14 1.19  |  2.00 3.07 6.67 7.95 19.39
                          ^^^ 여기가 완전히 비어 있다 (1.7배 간극)
```

1.5 는 그 빈 구간의 한가운데다. 아래로 1.26배 / 위로 1.33배 마진 — **임계를 ±25% 움직여도
분류가 한 칸도 바뀌지 않는다.** 물리적으로도 오버슈트 1.19배는 감쇠비 변화 수% 수준이지만
2배는 수십% 수준이다.

### 세 지표를 OR 로 묶는 이유 (그리고 부수적 발견)

| | 열화 구간에서의 거동 |
|---|---|
| ρ_overshoot | **가장 먼저 무너진다.** 2.00 ~ 19.39 |
| ρ_settle | 대부분 **1 미만** — 이득을 올리면 불안정 직전까지 응답은 계속 빨라진다 |
| ρ_rms_track | `k1.6_f50`(8.64) 하나 빼면 전부 ~1.00 |

즉 **과도 감쇠가 먼저 무너지고, 속응성과 정상상태 추종은 맨 마지막에 무너진다.**
속응성만 보고 튜닝하면 열화 구간에 들어간 걸 알 수 없다.

### 30조합 재분류 결과 — 안정 18 / 열화 5 / 불안정 7

```
filt_hz \ k_scale    1.0  1.2  1.4  1.6  1.8  2.0
            10        S    S    S    S    D    D
            15        S    S    S    S    D    X
            25        S    S    S    S    X    X
            35        S    S    S    D    X    X
            50        S    S    S    D    X    X
```

열화로 재분류된 5개: `k1.6_f35`(ρ_os 3.07), `k1.6_f50`(19.39), `k1.8_f10`(2.00),
`k1.8_f15`(6.67), `k2_f10`(7.95).

---

## [3] 안정 경계 정밀화 — `stability_filter_map.csv`

```
python scripts/run_stability_filter_map.py   ->  results/stability_filter_map.csv
```

filt_hz 8수준 × k_scale 10수준 = 80조합, 목표G 5.0 고정.
요청 격자는 k=1.4 부터지만 **k=1.0 을 기준선으로 함께 돌렸다** — 3구간 분류가
"같은 filt_hz 의 최저 이득 대비 배수"로 정의돼 있어 기준 행이 격자 안에 있어야
`stability_boundary` 와 같은 척도가 된다. 물리 루프는 `run_corner_pull_sweep.run_one`
을 그대로 import 해 쓰므로 기존 실험과 100% 동일하다.

```
filt_hz \ k   1.0  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.2  2.5
      10       S    S    S    S    S    D    D    D    X    X
      12       S    S    S    S    S    D    D    D    X    X
      15       S    S    S    S    D    D    D    X    X    X
      20       S    S    S    S    D    X    X    X    X    X
      25       S    S    S    S    X    X    X    X    X    X
      30       S    S    S    S    X    X    X    X    X    X
      40       S    S    S    D    X    X    X    X    X    X
      50       S    S    S    D    X    X    X    X    X    X
```

| filt_hz | 마지막 안정 k | 첫 열화 k | 첫 불안정 k | 열화대 폭 |
|---:|---:|---:|---:|---:|
| 10 | 1.7 | 1.8 | 2.2 | 3칸 |
| 12 | 1.7 | 1.8 | 2.2 | 3칸 |
| 15 | 1.6 | 1.7 | 2.0 | 2칸 |
| 20 | 1.6 | 1.7 | 1.8 | 1칸 |
| 25 | 1.6 | — | 1.7 | **0칸** |
| 30 | 1.6 | — | 1.7 | **0칸** |
| 40 | 1.5 | 1.6 | 1.7 | 1칸 |
| 50 | 1.5 | 1.6 | 1.7 | 1칸 |

두 가지가 나온다.

1. **경계는 filt_hz 가 올라갈수록 왼쪽으로 민다** (k 1.7 → 1.5). 확인됐다.
2. **filt_hz 25~30Hz 에서는 열화 구간이 아예 없다.** k=1.6 안정에서 k=1.7 리밋사이클로
   경고 없이 절벽처럼 떨어진다. **운용 기본값이 정확히 filt_hz=25.0** 이다
   (`pilot.py:53`). 이 설정에서는 이득 마진이 줄어드는 걸 미리 감지할 수 있는
   중간 신호가 없다.

### 지연시간(명령-실제 상호상관) — 안정성 대 속응성 맞교환

`lag_q_s` = 피치레이트 명령 `omega_sp_q` 와 실제 `omega_q` 의 정규화 상호상관 최대점.
3점 포물선 보간으로 샘플(8.3ms)보다 미세한 해상도. 검증: 알려진 지연 50ms → 49.97ms,
120ms → 116.6ms.

`xcorr_peak_q` 를 신뢰도로 같이 기록한다. 안정/열화 케이스는 0.88~0.98 이고
**불안정 케이스는 0.01~0.07 로 무너진다** — 리밋사이클에서는 응답이 명령과 무관해지므로
지연이라는 개념 자체가 성립하지 않는다. 그래서 아래 표는 불안정 칸을 비웠다.

lag [ms]:

```
filt_hz \ k     1.0    1.4    1.5    1.6    1.7    1.8    1.9    2.0
      10      203.6  153.1  138.6  101.4   94.7   91.8D 153.9D 249.7D
      15      204.7  160.4   95.9   93.3   89.5D 267.2D 273.9D    -
      25      205.6  174.4   89.7   88.9     -      -      -      -
      50      205.8  208.2  207.2    -       -      -      -      -
```
(D = 열화 구간)

* **이득이 지연을 지배하고, 필터는 지연에 거의 영향이 없다.** k=1.0 고정 시
  filt_hz 를 10 → 50 으로 5배 올려도 lag 는 203.6 → 205.8 ms 로 사실상 변화가 없다.
* **지연 최솟값은 마지막 안정 k_scale 에서 나온다.** filt 25Hz 기준 205.6 → 88.9 ms,
  **2.3배 빨라진다**. 경계를 넘어가면 더 살 게 없다 — 열화 구간에 들어서면 lag 가
  다시 올라간다(91.8 → 153.9 → 249.7).
* 따라서 맞교환은 "filt_hz 를 낮춰 마진을 벌고, 그 마진만큼 k 를 올려 지연을 줄인다" 가 된다.

**단서**: 이 스윕에는 **센서 잡음이 없다.** 필터의 존재 이유가 잡음 제거인데 그 비용이
모델에 없으므로, "낮은 filt_hz 가 무조건 유리하다" 로 읽으면 안 된다. 잡음을 넣은
후속 시험이 필요하다.

---

## [4] 러더 포화가 기체 한계인가 — `rudder_authority_analysis.csv`

```
python scripts/run_rudder_authority.py   ->  results/rudder_authority_analysis.csv
```

뱅크 30/35/40/45/50/55/60 × 속도 400/450KCAS × **요축 법칙 5종** = 70조합, 15000ft.
요축 법칙만 바꾸고 기체·고도·동압·나머지 축은 전부 동일한 대조 실험이다.

| 법칙 | r_sp | 의미 |
|---|---|---|
| `tan` | `g·tanφ/V` | 현행 |
| `sin` | `g·sinφ·cosθ/V` | 협조선회 body r 이론값 |
| `kin` | `ψ̇_실측·cosθ·cosφ` | 실측 선회율 기반 — 도달 불가능 성분이 0 인 유일한 지령 |
| `beta0` | (러더를 INDI 에서 떼고 β→0 PI) | **협조선회에 실제로 필요한 러더**를 실측 |
| `zero` | 러더 고정 0 | 러더 기여분 상한 |

### 결론: 기체 한계가 아니다. 세 가지 증거

**증거 1 — 지령식만 바꾸면 포화가 사라진다.** 같은 기체, 같은 동압, 같은 다른 축:

명령 포화율 [%]:

| 뱅크 | tan/400 | tan/450 | sin/400 | **kin/400** | **kin/450** |
|---:|---:|---:|---:|---:|---:|
| 30 | 94.5 | 91.3 | 81.2 | **3.0** | **1.4** |
| 40 | 97.8 | 96.4 | 90.2 | **2.9** | **2.1** |
| 45 | 98.0 | 96.3 | 91.6 | **3.3** | **2.1** |
| 55 | 97.6 | 95.9 | 92.8 | **3.6** | **2.1** |
| 60 | 97.2 | 95.8 | 93.3 | 57.1 | 69.8 |

뱅크 30~55도에서 `kin` 의 **정상상태 포화율은 정확히 0.0%** 다(남은 3% 는 롤인 과도구간).
기체는 손도 대지 않았다.

**증거 2 — 속도를 올려도 완화되지 않는다.** 400 → 450 KCAS 는 동압을 +25% 올리고
전타 요모멘트를 116,000 → 145,000 ft·lbf 로 올린다. 그런데 `tan` 의 포화율은
97.2 → 95.8% (뱅크 60), 94.5 → 91.3% (뱅크 30). **1~3%p 밖에 안 움직인다.**
러더 권한이 25% 늘었는데 포화가 그대로라면 원인은 권한이 아니다.
(`kin` 의 뱅크 60 잔여 포화는 속도를 올리면 오히려 **악화**된다: 57.1 → 69.8%.
동압 가설과 정반대다.)

**증거 3 — 러더 타면은 애초에 스톱 근처에도 안 간다.** 이게 가장 중요하다.

`fcs/rudder-cmd-norm = ±1` 은 **전타가 아니다.** F-16 native FLCS 를 통과한 실제 타면 각도:

| | 70조합 전체 최대 타면 | 기계 한계 | 비율 |
|---|---:|---:|---:|
| `rudder-pos-deg` | **12.11°** | ±30.0° (`f16.xml` `aerosurface_scale fcs/rudder-control`, range ±0.524rad) | **40%** |

정상상태 타면 각도 (뱅크 60 / 400KCAS):

| 법칙 | 명령 | 실제 타면 | 명령 포화 |
|---|---:|---:|---:|
| `tan` | −1.000 (스톱) | **4.33°** | 100% |
| `kin` | +1.000 (스톱) | 10.30° | 100% |
| `zero` | 0.000 | **7.26°** | 0% |

러더 명령을 **0으로 고정했을 때(7.26°)가 명령을 스톱까지 밀어붙였을 때(4.33°)보다
타면이 더 많이 움직인다.** native FLCS 의 요축은 `fcs/yaw-load-pid`(요레이트 +
측방가속도 피드백)가 명령을 적극적으로 되받아치는 폐루프이기 때문이다. 명령을 스톱에
물려두면 그 PID 가 대부분을 상쇄한다.

별도 확인 — 트림 상태에서 러더 명령만 1.0 스텝:

```
t=0.008s  타면 4.42°   (초기 스파이크)
t=0.200s  타면 0.37°   ← yaw-load-pid 가 되받아침
t=5.000s  타면 4.75°   (β=1.46° 와 평형)
peak = 4.75° / ±30°
```

**따라서 이 프로젝트의 모든 "러더 포화율" 은 "기체가 러더를 다 썼다"가 아니라
"FLCS 요축 명령 채널 입력이 스톱에 물렸다"는 뜻이다.** 이건 해석상 중요한 구분이다.

### 요모멘트 수지

I_zz = 67,072 slug·ft², `G0[2,2]` = −1.747 rad/s² (러더 명령 1단위당, q̄=510psf 에서 식별).

| | 400 KCAS | 450 KCAS |
|---|---:|---:|
| 전타 명령(=±1) 요모멘트 `N_rud_max` | 116,000 ft·lbf | 145,000 ft·lbf |
| `kin` 뱅크 45 정상상태 사용량 | 1,924 ft·lbf (명령 0.017) | 37,403 ft·lbf |
| 여유 | **60배** | 3.9배 |

### 솔직한 단서 — β=0 협조는 별개의 더 어려운 문제다

`beta0`(β→0 PI) 실행 결과, **β 를 정확히 0 으로 만드는 것**은 뱅크 50도 이상 / 400KCAS 에서
명령 채널을 다 쓰고도 달성되지 않는다(전타 명령에서도 β 가 1.40° 남는다).

다만 이건 스윕이 요구하던 것과 다른 문제다. 러더를 아예 안 쓰면(`zero`) β 는 뱅크 60에서
2.38° 에 그친다 — 무해한 수준이다. 그리고 기존 `results/rudder_zero_compare.csv` 가 보여주듯
**포화된 러더는 β 를 오히려 악화시킨다**(뱅크 60: 러더 0일 때 2.16° vs 포화 시 2.81°).

정리하면: 관측된 러더 포화는 지령 오류다(H2). β=0 정밀 협조는 이 모델에서 명령 채널
권한이 빠듯한 별개 항목이며, 현재 실험이 요구하는 것도 아니다.

---

## [5] 순간 기동 시험 — `run_g_onset_sweep.py`

```
python scripts/run_g_onset_sweep.py --kcas 400   ->  results/g_onset_15k400_summary.csv
python scripts/run_g_onset_sweep.py --kcas 450   ->  results/g_onset_15k450_summary.csv
```

3초 급당김, 목표G 3/5/7/9 × k_scale 5수준 × filt_hz 5수준 = 100조합 × 2속도, 15000ft, full AB.

### 먼저: G 계산식이 과대평가하고 있었다

corner_pull 계열은 하중배수를 기구학 근사로 계산한다:

```python
n_act = q * V / g + cos(phi)*cos(theta)      # run_corner_pull_sweep.py:148
```

이 식은 비행경로각이 기체와 같이 도는(γ̇ = q − α̇) **정상 선회**에서만 맞다.
3초 급당김은 α̇ 가 큰 구간이 전부다. JSBSim 이 직접 내는 `accelerations/Nz` 와 비교:

| 목표 | 기구학 `n_act` 피크 | **실제 `Nz` 피크** | 오차 |
|---:|---:|---:|---:|
| 3G | 2.994 | 2.949 | +0.05 |
| 5G | 4.982 | 4.771 | +0.21 |
| 7G | 6.939 | 6.468 | +0.47 |
| **9G** | **8.854** | **7.035** | **+1.82 (26%)** |

(15000ft/400KCAS, k_scale=1.0, filt 25Hz)

과대평가가 G 가 클수록 커진다. 스윕은 **`Nz` 기준으로 판정**하고 기구학 값은
`g_peak_kinematic` 으로 비교용 보존한다.

> 이건 `g_onset` 만의 문제가 아니다. `scripts/measure_g_envelope.py:244` 도 같은
> 기구학 식을 쓴다. `aircombat/control/limiter.py` docstring 의 "순간 봉투는
> 맞다(실측 피크 9.1G)" 라는 서술은 그 식에서 나온 값이므로 재확인이 필요하다.

### 9G 도달 가능 여부 — 불가능하다. 그리고 제어기 탓이 아니다

`Nz` 피크가 **k_scale, filt_hz, 속도와 무관하게 7.02~7.06G 에서 천장을 친다.**

목표 9G, `Nz` 피크 지도 (400 KCAS):

```
k_scale \ filt   10      15      25      35      50
    0.5        7.055   7.058   7.059   7.060   7.060
    0.75       7.045   7.046   7.046   7.046   7.046
    1.0        7.037   7.036   7.035   7.035   7.034
    1.5        7.017   7.021   7.028   7.031   7.032
    2.0        7.017   7.020   7.021   7.022   7.029
```

이득을 4배(0.5→2.0) 올려도 0.04G 밖에 안 움직인다. 제어기 튜닝의 문제가 아니다.

**INDI 를 완전히 빼고 생 풀애프트 스틱(`elevator-cmd-norm = −1.0`)으로 측정한
플랜트 자체의 최대 Nz:**

| 고도 | 속도 | **최대 Nz** | α 피크 | elevator 타면 |
|---:|---:|---:|---:|---:|
| 15000ft | 300 KCAS | 4.20 | 14.6° | −21.3° |
| 15000ft | 350 KCAS | 5.38 | 13.8° | −20.4° |
| 15000ft | **400 KCAS** | **6.68** | 13.3° | −19.6° |
| 15000ft | **450 KCAS** | **7.11** | 12.5° | −19.1° |

즉 **이 JSBSim F-16 은 15000ft 에서 9G 를 낼 수 없다.** 400KCAS 에서 6.68G 가 한계다.
INDI 가 낸 7.03G 는 플랜트 개루프 최대치와 사실상 같다 — **제어기는 기체가 줄 수 있는
것의 100% 를 이미 뽑고 있다.**

왜 못 가는지도 분해된다:

* `limiter_capped = 0` (200조합 전부). 프로젝트의 `CombinedLimiter` 는 한 번도 안 걸렸다 — `g_allowed` 가 내내 9.0 이었다. **공력 봉투 모델의 문제가 아니다.**
* α 피크가 12.5~13.3°. `f16.xml` 의 FLCS α 컷오프(28~30°) 근처에도 안 간다. **받음각 한계도 아니다.**
* elevator 타면이 −19.6° 에서 멈춘다. 기계 한계가 아니다.
* 남는 건 native FLCS 피치 채널의 폐루프 — `fcs/pitch-trim-error` 가 `pitch-rate-norm`(gain 6.2)과 `g-load-norm` 피드백으로 명령을 되받아친다. 러더 채널과 같은 구조다.

### 목표별 도달 (k_scale=1.0, filt 25Hz)

| 목표 | 400KCAS `Nz` | 도달률 | 400 최대 dG/dt | 450KCAS `Nz` | 도달률 |
|---:|---:|---:|---:|---:|---:|
| 3G | 2.949 | 98.3% | 4.48 G/s | 2.952 | 98.4% |
| 5G | 4.771 | 95.4% | 6.18 G/s | 4.820 | 96.4% |
| 7G | 6.468 | 92.4% | 8.02 G/s | 6.560 | 93.7% |
| 9G | 7.035 | **78.2%** | 11.08 G/s | 7.054 | **78.4%** |

3~5G 는 3초 안에 잘 들어간다. 7G 는 92~94% 로 아슬아슬하다. 9G 는 78% 에서 천장.

전체 200조합 기준: 3G 50/50 도달, 5G 33/50, 7G **0/50**, 9G **0/50**
(도달 기준 = 목표의 95%).

---

## 남은 것 / 권고

1. **`limiter.py` 의 9G 가정 재검토.** 이 플랜트는 15000ft 에서 6.7~7.1G 가 순간 한계다. `g_struct_max = 9.0` 은 실기 F-16 스펙으로는 맞지만 **이 모델에서는 도달 불가능한 값**이라, 리미터가 사실상 비활성 상태로 동작한다(200조합 전부 `limiter_capped=0`).
2. **기구학 G 근사를 `accelerations/Nz` 로 교체.** 최소한 `measure_g_envelope.py` 와 `run_corner_pull_sweep.py`. `SUSTAINED_G_15K` 표도 같은 식으로 만들어졌다면 재측정이 필요하다.
3. **요축 피드포워드 수정.** `--yaw-ff sin` 을 기본값으로 올릴지 결정 필요. 다만 `sin` 도 뱅크 60에서 포화가 93% 로 남는다(이 시험이 θ 를 트림값에 고정해 선회가 수평이 아니기 때문). 실전 적용은 `kin`(실측 ψ̇ 기반) 쪽이 맞다.
4. **INDI 안티와인드업.** 도달 불가능한 setpoint 가 주어지면 명령이 무조건 스톱까지 램프한다. 러더 포화의 직접 원인이다.
5. **잡음을 넣은 filt_hz 재시험.** 현재 맞교환 결론("낮은 filt_hz 가 유리")은 무잡음 조건의 산물이다.

---

## 산출 파일

| 파일 | 내용 |
|---|---|
| `results/heading_rate_verification.csv` | [1] heading 3방법 대조 + r_sp 이론 대조 |
| `results/stability_boundary_summary_classified.csv` | [2] 기존 30조합 3구간 재분류 |
| `results/stability_filter_map.csv` | [3] 80조합 정밀 경계 + 지연시간 |
| `results/rudder_authority_analysis.csv` | [4] 70조합 러더 권한 대조 실험 |
| `results/g_onset_15k400_summary.csv` | [5] 3초 급당김 100조합 @400KCAS |
| `results/g_onset_15k450_summary.csv` | [5] 3초 급당김 100조합 @450KCAS |
| `results/indi_step_coordinated_15k400_summary.csv` | 조건 통제 비교 (15000ft/400KCAS) |
| `results/indi_step_coordinated_summary.csv` | 기존 10000ft/350KCAS — heading 버그 수정 후 재생성 |

새 스크립트: `verify_heading_rate.py`, `classify_stability_bands.py`,
`run_stability_filter_map.py`, `run_rudder_authority.py`, `run_g_onset_sweep.py`
수정: `run_indi_step_sweep_coordinated.py`, `sweep_diagnostics.py`
